[package]
name = "quotes-exporter"
version = "0.1.0"
authors = ["Aleksei Lunacharskii <alun@katlex.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.20"
serde = "1.0.99"
serde_json = "^1.0"
google-sheets4 = "1.0.10"
hyper = "0.10.6"
hyper-rustls = "^0.6"
yup-oauth2 = "^1.0"
